### ISSUE TITLE
TTS bot no habla 

### ISSUE THREAD

**Issue by Telefonuka** [moonstar-x/discord-tts-bot#16]
Cuando lo asignamos a una sala para que entre a hablar y le damos con el comando $say, estando nosotros en el chat de voz, el bot responde Joined #General y no habla, solo manda ese mensaje.

![SharedScreenshot](https://user-images.githubusercontent.com/65088635/81482654-0c7e7400-920f-11ea-9ed7-8938cbb8447a.jpg)

**Comment by moonstar-x** [comment]
Esto está un poco raro porque acabo de probar en mi servidor y el bot sí funcionó. Sin embargo, revisé los logs del bot y encontré esto:

```text
May 09 18:29:33 moonstar-server npm[31900]: (6:29:33 PM) - [INFO] - User Telefonuka issued command say in La Locomotora Suarez.
May 09 18:29:33 moonstar-server npm[31900]: (6:29:33 PM) - [INFO] - Joined General in La Locomotora Suarez.
May 09 18:29:33 moonstar-server npm[31900]: (6:29:33 PM) - [INFO] - (TTS): Received googleTTS for hola putos with language 'en' and speed 1 in guild La 
May 09 18:29:33 moonstar-server npm[31900]: (6:29:33 PM) - [ERROR] - TypeError: Cannot destructure property `connection` of 'undefined' or 'null'.
May 09 18:29:33 moonstar-server npm[31900]:     at googleTTS.then (/home/discord/discord-tts-bot/src/classes/TTSPlayer.js:79:43)
May 09 18:29:33 moonstar-server npm[31900]:     at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

La proxima semana estaré libre, por lo que me dará tiempo para revisar esto y probar algunas cosas pero honestamente nunca he tenido este problema antes.

Podrías revisar que el bot tenga permisos para hablar en el canal en el que lo llamaste? Puedes intentar utilizarlo en otro canal? Si sigues dando comandos `$say ...` sucesivamente, te sigue diciendo que entró al canal una y otra vez (no debería suceder)?

De lo que entiendo por ver solo el log, el bot no detecta que esté en un canal de voz aún si en tu cliente parece estarlo, podría ser inclusive un error de la librería que utilizo, pero aún así no entiendo por qué sucede solo en tu servidor.

**Comment by Telefonuka** [comment]
hola!
revise todo lo que me dijiste y si, tenia todos los permisos activos, pero hoy paso algo inesperado, después de no andar por todo el dia ayer, hoy arranco bien como si nada. Voy a seguir testeandolo para ver si tiene algo que le dispare el bug asi te lo puedo avisar y lo patcheas.
Desde ya muchisimas gracias por responder tan rapido, tu bot es excelente y muy divertido, nos esta ayudando a pasar una amena cuarentena. Seguiremos en contacto.
Saludos desde Argentina,
AB

**Comment by moonstar-x** [comment]
Que bien que lo estes disfrutando. Sin embargo, el hecho de que te funcione ahora no son tampoco muy buenas noticias porque significa que el proxeso de debugging es mucho más complicado ahora. :(

Gracias por hacerme caer en cuenta de esto!

**Comment by moonstar-x** [comment]
Closed due to inactivity.
