### ISSUE TITLE
logger can't show Chinese character

### ISSUE THREAD

**Issue by ChiseLai** [moonstar-x/discord-tts-bot#19]
Hello there
I am a new user to github, where I have clone the bot and use it on my server
altho it works successfully for Chinese language, but everytime when a user use the command say with Chinese words together, the cmd logger seems to be failed on displaying the Chinese character
I have tried to change default CodePage of the cmd prompt to 65001 (unicode)
but it still fails to show it
Are there any way to fix this issue?

**Comment by moonstar-x** [comment]
Hey there, do you mind sharing a screenshot of your console?

**Comment by moonstar-x** [comment]
![image](https://user-images.githubusercontent.com/14969195/84163680-6012f600-aa37-11ea-99d8-a94e02edb730.png)

I just tried it with korean and chinese characters and they both show up on my end. Are you by any chance using cmd on windows?

**Comment by ChiseLai** [comment]
Sorry for reading that late
And yes, I’m using cmd to launch the bot
Is there other method to start the bot on window?

**Comment by moonstar-x** [comment]
It seems that it's got something to do with the font that cmd uses, which doesn't support UTF-8 characters. Maybe try changing the font as this [SuperUser thread](https://superuser.com/questions/1108443/utf8-characters-in-windows-10-bash-terminal) suggests. Moreover, I recommend you ise Windows Terminal (available from the Microsoft Store) rather than cmd.

**Comment by ChiseLai** [comment]
Gotcha, Imma give it a try if thats the case
Hope it works smoothly, Thanks :D

**Comment by ChiseLai** [comment]
It works, thanks a lot for the support
and willing to answer my dumb question 😂

**Comment by moonstar-x** [comment]
No worries, I'm glad you managed to fix it! :)
