### ISSUE TITLE
Bot don't say anything

### ISSUE THREAD

**Issue by Kedoichi** [moonstar-x/discord-tts-bot#23]
The Bot can connect to the voice channel but it doesn't say anything, I pretty sure that the bot has no error on my cmd

**Comment by moonstar-x** [comment]
Hey there, have you checked that you have no output on your console? This often happens when people try running it with no `ffmpeg` installed.

**Comment by Kedoichi** [comment]
how can i check it
I put it in $PATH already

**Comment by moonstar-x** [comment]
Well you can check if `ffmpeg` is installed if you try running in your console:

```
ffmpeg -v
```

Could you paste the console logs that you get when joining a channel and trying to say something?
