### ISSUE TITLE
Bot is not Verified so it can't join any more Discord Servers.

### ISSUE THREAD

**Issue by AX-7676** [moonstar-x/discord-tts-bot#25]
Discord with its new Bot policy won't allow bots, that are already in over 100 servers (This one being in 145 servers).
If you need it, here's the verification link https://disgd/bot-verification

**Comment by moonstar-x** [comment]
Hey there thanks for the heads up, I already sent a verification request and I'm waiting for an answer. Hopefully soon you'll be anle to add the bot to your server.

**Comment by AX-7676** [comment]
Ah, got it, then I guess all there is left to do it wait.

**Comment by moonstar-x** [comment]
I have just received a response from the Discord team, the bot is now verified. Thanks for the reminder!
