### ISSUE TITLE
Bot is not speaking anything

### ISSUE THREAD

**Issue by ChandanGaming** [moonstar-x/discord-tts-bot#36]
when I use command say it connects to the voice channel but did not say anything
![image_2021-07-15_233504](https://user-images.githubusercontent.com/86140577/125836036-8c63c17b-f566-4ed5-b46d-76271ea0f0d7.png)

**Comment by moonstar-x** [comment]
This isn't a bug, the console is telling you that you need `ffmpeg`.

I'm seeing that you're trying to use Repl.it, I've seen people having issues with it before. If I remember correctly, [they removed `ffmpeg` some time ago and then re-added it](https://replit.com/talk/ask/Installing-FFmpeg/28721), however it kinda sounds like they're removing it again.

You could try remaking a new Repl.it instance and see if that one works.

You could also try installing `ffmpeg`, I believe you don't get root permissions in those instances, so installing something through its package manager may not be possible, but you could try installing it through npm:

```
npm install -g ffmpeg-static
```

Or,

```
npm install ffmpeg-static
```

> I'm not sure about the latter, this one would just install the binary to `node_modules` and I'm not sure if `prism` is aware of the `node_modules` binary path.

In any case, I've never used Repl.it before, nor plan on using it...

**Comment by ChandanGaming** [comment]
Thank you bro it's working now

**Comment by moonstar-x** [comment]
I'm glad it's working now! :)
