### ISSUE TITLE
I have coming this issue now pls tell me the solution

### ISSUE THREAD

**Issue by ChandanGaming** [moonstar-x/discord-tts-bot#38]
#### :confused: Question

> When I execute the Say command it shows this and doesn't say anything
![image_2021-07-19_115115](https://user-images.githubusercontent.com/86140577/126112160-0237bae7-5158-409d-98ed-1dbba06d7f89.png)

**Comment by moonstar-x** [comment]
Hmm, weird. Normally `@discordjs/opus` should be installed. You could probably try removing `node_modules` and reinstalling the dependencies:

```
rm -rf node_modules && npm install
```

If after doing that it still doesn't work, try installing `opusscript`:

```
npm install opusscript
```

**Comment by moonstar-x** [comment]
I'm gonna close this because of inactivity. I assume that the above recommendation has fixed your issue.

If you're still having problems with this, feel free to re-open this issue.
