### ISSUE TITLE
multiple voices to differentiate different speakers?

### ISSUE THREAD

**Issue by mabelmabelmabelmabel** [moonstar-x/discord-tts-bot#56]
#### :zap: Describe the New Feature

multiple voices, created either by accessing different engines or changing up generated voice lines somehow or whatever would be easiest to do so a larger number of people can talk in a conversation using tts without sounding like the same person

#### :pencil2: Functionality

different prefixes or modifiers or whatever (i.e $say1, $say2, $say3, etc) that would make the voice sound different. maybe it could recognize the requests of different users and automatically assign them voices for consistency and ease of use but that would probably be way way harder

#### :question: Additional Information

my friendgroup has been using say and aeiou for this purpose but it stops working almost immediately once more than two people start using it and aeiou isn't very good for talking anyway because it's much quieter than say

**Comment by moonstar-x** [comment]
Hey there, thanks for the suggestion. 

I think it would be better to have the option to set the defaults for each user.

Once I finish my college semester I can go for this, it shouldn't be that complicated.

**Comment by LuciusNeverSeen** [comment]
throw new Error('FFmpeg/avconv not found!'); whats that?

**Comment by moonstar-x** [comment]
>  throw new Error('FFmpeg/avconv not found!'); whats that?

It means that you do not have ffmpeg installed. Check the [requirements](https://github.com/moonstar-x/discord-tts-bot#requirements), there's a guide there that tells you how to install it in case you're on windows.

If you're using repl.it, try recreating your repl and/or running `npm i ffmpeg-static`.

Next time create a separate issue, since your question has nothing to do whth the topic of this issue. :)

**Comment by LuciusNeverSeen** [comment]
Thank you so much I fixed it :3

Vào Th 4, 15 thg 12, 2021 vào lúc 09:07 moonstar-x <
***@***.***> đã viết:

**Comment by moonstar-x** [comment]
Added in #58.
