### ISSUE TITLE
Slash Commands Not Registering?

### ISSUE THREAD

**Issue by TheCrafters001** [moonstar-x/discord-tts-bot#63]
#### :bug: Describe the Bug

Slash commands for the bot are not appearing

#### :pencil2: Steps to Reproduce

> Followed procedure (Updated from V3 to v4.0.2)

#### :confused: Expected Behavior

Expected slash commands to work

#### :scroll: Log

``` text
The normal junk when starting the bot. Nothing about the user sending a command
```

#### :camera: Screenshots

> Paste a screenshot of the bug (if applicable).

#### :question: Other Information

* Node Version: `16.13.2`

**Comment by moonstar-x** [comment]
Hey, have you ran `npm run deploy` before doing the start?

Also, this has been happening to some poeple, try re-inviting your bot to your server but use the generated URL from the `Oauth2 URL Generator` page in the developer application portal.

Make sure you choose the `bot` and `application.commands` scopes and the correct permissions as they're described in the README.

**Comment by moonstar-x** [comment]
Let me know if the above solution helps you.

**Comment by TheCrafters001** [comment]
Ah, I forgot to re-invite it with the `application.commands` scope. My bad. It works now.

**Comment by moonstar-x** [comment]
Nice,

I'm going to pin this issue for anyone that comes across this.
