### ISSUE TITLE
Settings are broken

### ISSUE THREAD

**Issue by twilight-sparkle-irl** [moonstar-x/discord-tts-bot#74]
#### :bug: Describe the Bug

> You cannot have both a custom speed and a custom language at the same time. This also applies to every other provider with more than two settings, none of which currently exist.

#### :pencil2: Steps to Reproduce

> 1. /google_set_my language fr
> 2. /my_settings, see language french, speed normal
> 3. /google_set_my speed slow
> 4. /my_settings, see language english, speed slow

#### :confused: Expected Behavior

> Language French, speed slow.

#### :camera: Screenshots

> ![image](https://user-images.githubusercontent.com/15254673/156943964-57a53d84-133d-45fb-b34b-8c5fded097c6.png)

**Comment by moonstar-x** [comment]
Thank you for the report, I'm gonna check it out. I think it may be that the cached data does not get updated properly but the one in the database does.

**Comment by moonstar-x** [comment]
Fixed in #76.
